language: php

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  
notifications:
    email: false
